### ISSUE TITLE
Invalid SYSCONF Errors - Vive 5.0-250

### ISSUE THREAD

**Issue by CyberGamerly** [CarlKenner/dolphin#122]
I don't know if this is an issue with the program or my computer, there are absolutely no results on google of anyone else having this issue. I downloaded the program off the wordpress site and installed the client, Runtime, and Direct3D. When I launch the .exe, I get the error message "Unknown entry type 6 in SYSCONF (IPL.TID@17f5)!" before the menu has a chance to load in. After clicking ok, the menu loads in and I get the error message "Trying to read from invalid SYSCONF" continuously until I kill the program in task manager. I have no idea what could be the issue (besides the SYSCONF of course), all I did was download and install Dolphin VR and opened it using the shortcut on my desktop.

**Comment by Robospot** [comment]
Do you have another dolphin install on your system? If so try creating a blank .txt file in the Dolphin VR folder (C:\Program Files\Dolphin VR) and renaming it "portable.txt" without the quotes. I believe this issue is caused by a change in how vanilla dolphin stores it's system configuration in more recent builds.

**Comment by CyberGamerly** [comment]
This surprisingly worked. Thank you, everything is working as it should.
