### ISSUE TITLE
Demangler causes crash when opening Super Mario Sunshine NTSC-U .map file

### ISSUE THREAD

**Issue by cegli** [CarlKenner/dolphin#38]
I made a GMSE01.map file by applying the signature file from the PAL version to the NTSC version.  With the demangler, it crashes on this line of the .map file:

802a9484 000003a8 802a9484 0 insert__Q27JGadget116TVector<Q216TDrawSyncManager19TDrawSyncTokenRange,Q27JGadget53TAllocator<Q216TDrawSyncManager19TDrawSyncTo

If I replace that line with:

802a9484 000003a8 802a9484 0 insert__Q27JGadget

It works fine.  It looks like the crash occurs at line 402 of PPCSymbolDB.cpp:

return result + "__" + name.substr(p, std::string::npos);

Replacing that line with "return result;" allows the game to load correctly.  Deleting the .map file also does the same.  I tried for a little bit to figure out how to fix it, but I'm giving up for now.

**Comment by CarlKenner** [comment]
Sorry. I tried to make it error tolerant. For example, insert__Q27JGadget is actually invalid, because the Q2 part means that there are two parts (one namespace and one name) following, and the 7 indicates a custom type name that is 7 letters long, so it would expect another type following.

In the full name, that second part is supposed to be a 116 character custom type name. But there are only 107 characters following it. You can tell that some characters are missing because there are two opening "<" and no ">". Because I'm a human, I know the missing characters must be "kenRange>>" but there is no way for the computer to work that out. Also it would normally be followed by "Fv" or something longer to indicate it is a function, but that got truncated too.

BTW, I'm currently ignoring the templates inside names and not bothering to demangle them.

I guess it should be demangled to:
JGadget::TVector<Q216TDrawSyncManager19TDrawSyncTokenRange,Q27JGadget53TAllocator<Q216TDrawSyncManager19TDrawSyncTo::insert

But if I was processing templates properly, I would demangle it to:
JGadget::TVector<TDrawSyncManager::TDrawSyncTokenRange,Gadget::TAllocator<TDrawSyncManager::TDrawSyncTo>>::insert

Or should I include a "..." when there are missing characters?

Anyway, I'll see what I can do to stop it crashing. I'm a bit busy right now though.

**Comment by cegli** [comment]
Ah, yes I was wondering if it had to do with the fact that it was truncated.  "..." seems like a reasonable solution.  The demangler is pretty nice by the way, make the functions a lot more readable.

**Comment by CarlKenner** [comment]
I also wanted to make the functions a lot more findable. Having the class name on the left where it belongs instead of on the right, means functions are sorted logically by namespace and class rather than almost randomly.

**Comment by CarlKenner** [comment]
This issue cropped up again recently, when Metroid Prime's map file was crashing it.
I think it's now fixed.
